pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo "Cloning the latest application version"
                git branch: 'main', url: 'https://github.com/Emmylong1/CloudHight.git'
            }
        }

        stage('Change Directory') {
            steps {
                dir('/var/lib/jenkins/workspace/Cloudhight-CICD/application-assessment-repo') {
                    // This stage is just to change the directory
                    echo "Changed directory to application-assessment-repo"
                }
            }
        }

        stage('Test') {
            steps {
                echo "Running Unit Testing"
                sh "mvn clean package"
                echo "Unit Testing Successful"
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building Docker image"
                sh "docker build -t cloudhight ."
                echo "Docker image built successfully"
            }
        }

        stage('Docker Run') {
            steps {
                echo "Starting Docker container"
                sh "docker run -d -p 8085:8085 --name cloudhight cloudhight"
                echo "Docker container started successfully"
            }
        }
    }
}
